# arxivの学問領域の指定
subject: 'cs'

# 検索キーワード
keywords:
        graph neural network: 3
        reinforcement learning: 3
        graph embedding: 2
        persistent memory performance: 3
        memory access pattern: 2
