# arxivの学問領域の指定
subject: 'cs'

# 検索キーワード
keywords:
        graph neural network: 3
        graph convolutional network: 4
        graph attention network: 3
        graph benchmark: 3
        explainable gnn: 4
        explaining: 2
        gnn performance: 3
        performance model: 2
        stock prediction: 2
        graph embedding: 2
        persistent memory: 3
        memory access pattern: 2
        optane: 2
        nvram: 3
        reram: 3
