# arxivの学問領域の指定
subject: 'cs'

# 検索キーワード
keywords:
        graph neural network: 3
        reinforcement learning portfolio: 3
        stock prediction: 2
        graph embedding: 2
        persistent memory performance: 3
        memory access pattern: 2
        optane memory: 2
        optane graph: 4
